---

- set_fact:
    wp_repo_checkout_dir="~/Downloads/{{ wp_repo_name }}"

- name: "Checkout and update {{ wp_repo_name }} repository"
  git:
    repo: "https://mcajani:Cj587064@bitbucket.org/mcajani/{{ wp_repo_name }}.git"
    dest: "{{ wp_repo_checkout_dir }}"
    update: yes
  become: True
  become_user: "{{ default_user }}"

- name: Retrieving wp-configs
  import_tasks: retrieve-wp-configs.yml

- name: "Create {{ wp_db_name }} DB schema"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: "root"
    login_password: "{{ default_user_password }}"
  become: True
  become_user: "{{ default_user }}"

# TODO1: create db user too
# TODO3: schema with right collate
# TODO4: if safe, import schema from dump -> NI: local ansible task not binded to provisioning
# TODO5: fetch dump from ftp backup
# TODO6: ? trigger remote db backup ? -> NO: ithemes security
