---

- set_fact:
    wp_repo_checkout_dir="~/Downloads/{{ wp_repo_name | default('wp') }}"

- name: "Checkout and update {{ wp_repo_name }} repository"
  git:
    repo: "https://mcajani:Cj587064@bitbucket.org/mcajani/{{ wp_repo_name }}.git"
    dest: "{{ wp_repo_checkout_dir }}"
    update: yes
  become: True
  become_user: "{{ default_user }}"
  when: wp_repo_name is defined

- name: Retrieving wp-configs
  import_tasks: retrieve-wp-configs.yml
  when: wp_repo_name is defined

- name: "Create {{ wp_db_name }} DB schema"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: "root"
    login_password: "{{ default_user_password }}"
  become: True
  become_user: "{{ default_user }}"
  when: wp_db_name is defined

# TODO1: create db user too
# TODO2: db properties from wp config
# TODO3: schema with right collate
# TODO4: if safe, import schema from dump
# TODO5: dump from ftp backup
# TODO6: ? trigger remote db backup ?
