---

- name: Install prerequisites
  import_tasks: install-prerequisites.yml

- set_fact:
    apache_document_root="/home/{{ params.user.username }}/Downloads/{{ wp_hostname | mandatory }}"

- set_fact:
    wp_checkout_dir="{{ apache_document_root }}/{{ wp_path | default('') }}"

- name: "Checkout and update git repository for {{ wp_hostname }}"
  git:
    repo: "{{ wp_repo_url }}"
    dest: "{{ wp_checkout_dir }}"
    update: yes
  become: True
  become_user: "{{ params.user.username }}"
  when: wp_repo_url is defined

- name: "Mirror FTP for {{ wp_hostname }}"
  command: 'lftp {{ wp_ftp.host }} -u {{ wp_ftp.username }},{{ wp_ftp.password }} -e "set ftp:ssl-allow no; glob -d mirror {{ wp_ftp.remote_dir }} {{ wp_checkout_dir }} --parallel=4 --only-newer --exclude .git; quit;"'
  become: True
  become_user: "{{ params.user.username }}"
  when: wp_ftp is defined

- name: Retrieving wp-configs
  import_tasks: retrieve-wp-configs.yml

- name: "Create {{ wp_db_name }} DB schema"
  mysql_db:
    name: "{{ wp_db_name }}"
    collation: "{{ wp_db_collate }}"
    encoding: "{{ wp_db_charset }}"
    state: present
    login_user: "root"
    login_password: "{{ params.user.password }}"
  become: True
  become_user: "{{ params.user.username }}"

- name: "Create {{ wp_db_user }} DB user"
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    login_user: "root"
    login_password: "{{ params.user.password }}"
  become: True
  become_user: "{{ params.user.username }}"

- name: "Count tables in {{ wp_db_name }} DB schema"
  command: "mysql -uroot -p{{ params.user.password }} -N -B -e \"SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '{{ wp_db_name }}';\""
  register: wp_db_name_tables_cmd
- set_fact:
    wp_db_name_tables_count: "{{ wp_db_name_tables_cmd.stdout }}"

- name: "Find {{ wp_db_name }} DB schema dump"
  shell: "ls -Art {{ wp_checkout_dir }}/{{ db_dump_relative_path }}/*.zip | tail -n 1"
  register: found_db_schema_cmd
- set_fact:
    found_db_schema_dump: "{{ found_db_schema_cmd.stdout }}"

- set_fact:
    import_dump_needed: '{{ found_db_schema_dump != "" and wp_db_name_tables_count == "0" }}'
    import_dump_file: "/tmp/{{ wp_db_name }}.sql"

- name: "Unzip {{ wp_db_name }} DB schema dump"
  unarchive:
    src: "{{ found_db_schema_dump }}"
    dest: "{{ import_dump_file }}"
    remote_src: True
  become: True
  become_user: "{{ params.user.username }}"
  when: import_dump_needed

- name: "Import {{ wp_db_name }} DB schema dump"
  mysql_db:
    name: "{{ wp_db_name }}"
    collation: "{{ wp_db_collate }}"
    encoding: "{{ wp_db_charset }}"
    state: import
    target: "{{ import_dump_file }}"
    login_user: "root"
    login_password: "{{ params.user.password }}"
  become: True
  become_user: "{{ params.user.username }}"
  when: import_dump_needed

- name: "Cleanup temporary {{ wp_db_name }} DB schema dump"
  file:
    state: absent
    path: "{{ import_dump_file }}"
  become: True
  become_user: "{{ params.user.username }}"

- name: "Setup vhost for {{ wp_hostname }}"
  template:
    src: "apache-vhost.conf.j2"
    dest: "/etc/apache2/sites-enabled/{{ wp_hostname | mandatory }}-vhost.conf"
    force: yes
    mode: 0644
  become: True

- name: "Add /etc/hosts entry to resolve {{ wp_hostname }} locally"
  lineinfile:
    path: /etc/hosts
    regexp: ".*{{ wp_hostname }}.*"
    line: "127.0.0.1 {{ wp_hostname }}"
  become: True

- name: Restart apache
  service:
    name: apache2
    state: restarted
  become: True
