---

- name: "Checkout and update {{ wp_repo_name }} repository"
  git:
    repo: "https://mcajani:Cj587064@bitbucket.org/mcajani/{{ wp_repo_name }}.git"
    dest: "~/Downloads/{{ wp_repo_name }}"
    update: yes
  become: True
  become_user: "{{ default_user }}"
  when: wp_repo_name is defined

- name: "Create {{ wp_db_name }} DB schema"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: "root"
    login_password: "{{ default_user_password }}"
  become: True
  become_user: "{{ default_user }}"
  when: wp_db_name is defined
