---

- set_fact:
    wp_repo_name="{{ wp_repo_url.rsplit('/', 1)[1].rsplit('.')[0] }}"

- set_fact:
    wp_repo_checkout_dir="/home/{{ default_user }}/Downloads/{{ wp_repo_name }}"

- name: "Checkout and update {{ wp_repo_name }} repository"
  git:
    repo: "{{ wp_repo_url }}"
    dest: "{{ wp_repo_checkout_dir }}"
    update: yes
  become: True
  become_user: "{{ default_user }}"

- name: Retrieving wp-configs
  import_tasks: retrieve-wp-configs.yml

- name: "Create {{ wp_db_name }} DB schema"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: "root"
    login_password: "{{ default_user_password }}"
  become: True
  become_user: "{{ default_user }}"

- name: "Create {{ wp_db_user }} DB user"
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "localhost.{{ wp_db_name }}:ALL"
    state: present
    login_user: "root"
    login_password: "{{ default_user_password }}"
  become: True
  become_user: "{{ default_user }}"

# TODO3: schema with right collate
# TODO4(future): if safe, import schema from dump -> NI: local ansible task not binded to provisioning
# TODO5(future): fetch dump from ftp backup
# TODO6(future): ? trigger remote db backup ? -> NO: ithemes security
