---

- set_fact:
    wp_configs_working_dir="/tmp/wp_configs_for_{{ wp_repo_name }}"

- name: Init temporary working directory
  file:
    state: directory
    path: "{{ wp_configs_working_dir }}"
  become: True
  become_user: "{{ default_user }}"

- name: Add scripts to working dir
  template:
    src: "{{ item }}"
    dest: "{{ wp_configs_working_dir }}"
    force: no
    mode: 0644
  with_items:
    - get-wp-config.php
    - wp-settings.php
  become: True
  become_user: "{{ default_user }}"

- name: Copy wp-config.php to working dir
  command: "cp {{ wp_repo_checkout_dir }}/wp-config.php {{ wp_configs_working_dir }}"
  become: True
  become_user: "{{ default_user }}"

- name: Register DB_NAME config
  command: "php {{ wp_repo_checkout_dir }}/get-wp-config.php DB_NAME"
  register: get_db_name

- set_fact:
    wp_db_name="{{ get_db_name.stdout }}"

- name: Cleanup temporary working directory
  file:
    state: absent
    path: "{{ wp_configs_working_dir }}"
  become: True
  become_user: "{{ default_user }}"
